# Generated by Django 2.2 on 2023-08-22 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230818_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='ending',
            new_name='track_ending',
        ),
    ]
