# Generated by Django 4.0 on 2021-12-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_storytag'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='api.StoryTag'),
        ),
    ]
