# Generated by Django 4.0 on 2021-12-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_story_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
