# Generated by Django 4.0 on 2021-12-28 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_story_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.DeleteModel(
            name='StoryTag',
        ),
    ]
