# Generated by Django 4.0 on 2021-12-29 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='active_users',
            field=models.ManyToManyField(blank=True, related_name='active_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='banner_color',
            field=models.CharField(blank=True, default='ec4a4e', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='code',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='room',
            name='inactive_users',
            field=models.ManyToManyField(blank=True, related_name='inactive_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='invite_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='invite_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='mode',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('closed', 'Closed')], default='private', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='playlist_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='playlist_image_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default='New Room', max_length=150),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_line', models.CharField(default='Jammer', max_length=50)),
                ('access_token', models.CharField(blank=True, max_length=70, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=70, null=True)),
                ('authorized', models.BooleanField(default=False)),
                ('color', models.CharField(default='1c71ca', max_length=6)),
                ('new_user', models.BooleanField(default=True)),
                ('online_count', models.IntegerField(blank=True, default=0)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('most_recent_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='most_recent_name', to='api.room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
