# Generated by Django 4.0 on 2021-12-29 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_roommode_room_active_users_room_banner_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='most_recent_room',
        ),
    ]
