# Generated by Django 4.0 on 2021-12-29 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_userprofile_most_recent_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='active_users',
        ),
        migrations.RemoveField(
            model_name='room',
            name='inactive_users',
        ),
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
    ]
