# Generated by Django 4.0 on 2021-12-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_room_active_users_remove_room_inactive_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='default', max_length=30, primary_key=True, serialize=False),
        ),
    ]
