# Generated by Django 4.0 on 2021-12-29 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_remove_room_id_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='active_users',
            field=models.ManyToManyField(blank=True, related_name='active_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='inactive_users',
            field=models.ManyToManyField(blank=True, related_name='inactive_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='most_recent_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='most_recent_name', to='api.room'),
        ),
    ]
