# Generated by Django 3.1.4 on 2021-12-30 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_room_active_users_room_inactive_users_room_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_index', models.IntegerField(blank=True, default=0)),
                ('progress_ms', models.IntegerField(blank=True, default=0, null=True)),
                ('last_action', models.DateTimeField(blank=True, null=True)),
                ('last_song_end', models.DateTimeField(blank=True, null=True)),
                ('playing', models.BooleanField(blank=True, default=False)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
    ]
