# Generated by Django 3.1.4 on 2022-01-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211230_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
