# Generated by Django 3.1.4 on 2022-11-07 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_auto_20220112_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('code', models.CharField(default='default', max_length=30, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('public', 'Public'), ('friendsonly', 'Friends Only'), ('private', 'Private'), ('closed', 'Closed')], default='private', max_length=50)),
                ('invite_code', models.CharField(blank=True, max_length=6, null=True)),
                ('invite_time', models.DateTimeField(blank=True, null=True)),
                ('song_index', models.IntegerField(blank=True, default=0)),
                ('progress_ms', models.IntegerField(blank=True, default=0, null=True)),
                ('last_action', models.DateTimeField(blank=True, null=True)),
                ('last_song_end', models.DateTimeField(blank=True, null=True)),
                ('playing', models.BooleanField(blank=True, default=False)),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='party_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
