# Generated by Django 3.1.4 on 2022-11-12 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_party_partymode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='most_recent_room',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_party', to='api.party'),
        ),
    ]
