# Generated by Django 3.1.4 on 2022-11-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20221112_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='spotify_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
