# Generated by Django 3.1.4 on 2022-11-19 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_notification_partyinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='partyinvite',
            name='party',
            field=models.ForeignKey(default='ohuiwe', on_delete=django.db.models.deletion.CASCADE, to='api.party'),
            preserve_default=False,
        ),
    ]
