# Generated by Django 3.1.4 on 2023-07-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_friendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
