# Generated by Django 3.1.4 on 2023-08-06 19:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0023_artist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
        migrations.DeleteModel(
            name='NotificationAction',
        ),
        migrations.DeleteModel(
            name='NotificationType',
        ),
        migrations.DeleteModel(
            name='RoomMode',
        ),
    ]
