# Generated by Django 3.1.4 on 2023-08-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20230806_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='last_action',
            new_name='playback_last_action',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='song_index',
            new_name='track_index',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='last_song_end',
            new_name='track_last_end',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='progress_ms',
            new_name='track_progress_ms',
        ),
        migrations.AddField(
            model_name='party',
            name='context_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='track_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
